export const CATLOADINGSUCCESS="CATLOADINGSUCCESS";
export const CATLOADINGFAILED="CATLOADINGFAILED";
export const SETCAT="SETCAT";
export const SETSUBCAT="SETSUBCAT";
export const SETSUBSUBCAT="SETSUBSUBCAT";