export const REQUESTLOADEDWITHSUCCESS="REQUESTLOADEDWITHSUCCESS";
export const REQUESTLOADEDWITHERROR="REQUESTLOADEDWITHERROR";
export const STARTBUFFERING="STARTBUFFERING";
export const ENDBUFFERING="ENDBUFFERING";


export const UPDATEREQUEST="UPDATEREQUEST";
export const REMOVEREQUEST="REMOVEREQUEST";
export const UPDATEREQUESTSTATUS="UPDATEREQUESTSTATUS";