export const REQUESTLOADEDWITHSUCCESS="REQUESTLOADEDWITHSUCCESS";
export const REQUESTLOADEDWITHERROR="REQUESTLOADEDWITHERROR";
export const STARTBUFFERING="STARTBUFFERING";
export const ENDBUFFERING="ENDBUFFERING";


export const UPDATEREQUEST="UPDATEREQUEST";
export const REMOVEREQUEST="REMOVEREQUEST";
export const UPDATEREQUESTSTATUS="UPDATEREQUESTSTATUS";

export const SET_MY_LAT_LONG="SETMYLATLONG";
export const SET_MY_PERSONAL_LAT_LONG="SETMYPERSONALLATLONG";